### ISSUE TITLE
Is this going to replace hub?

### ISSUE THREAD

**Issue by rijkvanzanten** [github/homebrew-gh#11]
Hi there! 👋 

Always excited to see GH launch new tools and features. That being said, how does this compare/relate to [`hub`](https://github.com/github/hub)?

**Comment by vilmibm** [comment]
hi!

there are no plans to replace or discontinue `hub`. `gh` is very inspired by it but is more of a sister project; it shares some code but it is largely a place for trying new ideas out about having GitHub more accessible from the terminal.

We've been thinking of `hub` as a git proxy _flavored_ with GitHub; `gh` is a terminal-based _version_ of GitHub.

I hope that helps!

**Comment by rijkvanzanten** [comment]
Ahh, so am I right in understanding that one might:

* use `hub` to checkout pull requests made to a repo, and
* use `gh` to get a list of the 5 newest issues marked with label 'high priority'

?

It will be interesting to see where the line will be drawn between the two 🙂 Is `gh` going to allow cloning repos, or should you use `hub` for that, etc

**Comment by ampinsk** [comment]
Hey @rijkvanzanten thanks for the question! To clarify, you actually _can_ use `gh` for both of those things! To checkout pull requests, you can use `gh pr checkout [number|branch|url]`. We knew this was a popular command in hub so we made sure to include it 😄 

As you can see, we are definitely still figuring out these lines. We would love to hear more thoughts and feedback as you use it more.

Thanks again!
