### ISSUE TITLE
gh fails when github.com isn't set as a remote other than `origin`

### ISSUE THREAD

**Issue by cgranade** [github/homebrew-gh#7]
Whenever running a command with `gh` that connects to the server in a repo, I get the following error:

```pwsh
PS> gh issue list
graphql error: 'Could not resolve to a User with the username ''.'
```

This repo has two remotes: `origin` is set to a local prototype, and `public` is set to the upstream GitHub repository.

**Comment by mislav** [comment]
Hi @cgranade thank you for the report!

We will work on improving matching git remotes to GitHub repos. In the meantime, you can rename your `public` remote to either "upstream" or "github" and `gh` should be working for your repo then.

**Comment by mislav** [comment]
Hi @cgranade, we're working on improving the remote parsing logic here: https://github.com/cli/cli/pull/266

In the meantime, I'm going to go ahead and close this issue since we're cleaning up issues in this repo. Thank you for reporting! 🙇
