### ISSUE TITLE
gh vs hub?

### ISSUE THREAD

**Issue by elashpear** [github/homebrew-gh#8]
So apparently, GitHub now has two CLI tools, this one and [hub](https://github.com/github/hub). As far as I can tell they are trying to solve similar problems. What's the long-term support plan? Is this one supposed to replace hub?

**Comment by mislav** [comment]
Hi, this is a great question, and one that we (the GitHub CLI team) intend to clarify further in the near future as we unroll more documentation for `gh`.

In the meantime, I will provide my own commentary as the maintainer of hub:

It's correct that `gh` and hub solve similar problems; as of now both have features for working with issues and pull requests in the current repo, for example. There will inevitably be some overlap between what these tools do, but `gh` does not aim to implement everything that hub does. Instead, we are reimagining what a GitHub command-line experience can be like from the ground up.

For now, nothing changes for hub: it will still work and it will receive bug fixes for the foreseeable future.

**Comment by elashpear** [comment]
Thanks. I have been considering doing some release automation at work using a GitHub client so maybe I should look at this tool instead of hub (or perhaps raw GraphQL API)
