### ISSUE TITLE
graphql error bad credentials

### ISSUE THREAD

**Issue by saiqulhaq** [github/homebrew-gh#9]
I got following error after authorized the app

![image](https://user-images.githubusercontent.com/1275215/71335058-625dc280-2573-11ea-90e7-defd3c088c10.png)

following is my `git remote -v`

```
https   https://github.com/xxx/xxx.git (fetch)
https   https://github.com/xxx/xxx.git (push)
origin  git@github.com:xxx/xxx.git (fetch)
origin  git@github.com:xxx/xxx.git (push) 
```

**Comment by mislav** [comment]
Hi thank you for reporting!

Does this happen every time you try?

**Comment by elashpear** [comment]
I am also seeing this issue every time I try to authorize GH. I am prompted to auth in my browser. After entering my password, I see the following message in the browser:

```
Authentication successful.
You have completed logging into GitHub CLI.
You may now close this tab and return to the terminal.
```

However, `gh` displays the following error:
```
Notice: authentication required
Press Enter to open github.com in your web browser...
http error, 'https://api.github.com/graphql' failed (401): 'Bad credentials'
```

I see the GitHub CLI OAuth app appear in my profile but it says "never used".

Not sure if this is related, but my work account (this one) now uses Okta SSO. I don't know what this means for your specific auth scheme but it has introduced complications for using certain auth schemes.

This is my `git remote -v`:
```
origin	git@github.com:github/homebrew-gh.git (fetch)
origin	git@github.com:github/homebrew-gh.git (push)
```

**Comment by saiqulhaq** [comment]
yes, it does

I use normal git command
no longer use `gh` at the moment

**Comment by mislav** [comment]
Hi all, thank you for reporting the "bad credentials" error. We've pushed a release that tweaks some of the authentication process; if you were affected by this would you please try it out? https://github.com/github/gh-cli/releases/tag/v0.4.0

We've also improved error messages, so you might get more useful error output in your terminal that you can share us to help us debug. Additionally, you may set the `DEBUG=oauth` environment variable to enable more verbose debugging of OAuth flow operations. If you do enable this and share the output with us, please make sure to first _redact anything that looks like your personal token_. Thank you!

**Comment by saiqulhaq** [comment]
the link doesn't work https://github.com/github/gh-cli/releases/tag/v0.4.0

**Comment by mislav** [comment]
@saiqulhaq Sorry for the bad link. It's this one https://github.com/github/homebrew-gh/releases/v0.4.0

**Comment by saiqulhaq** [comment]
no worries

it works now

```
~/.c/h/h/app ❯❯❯ gh pr list                                                                                                                                              develop
Notice: authentication required
Press Enter to open github.com in your browser...
Authentication complete. Press Enter to continue...


Pull requests for xxx/xxx

#507  Bump swiper from 4.5.0 to 5.3.0              dependabot/npm_and_yarn/swiper-5.3.0
#487  Bump dry-validation from 0.11.2 to 1.4.1     dependabot/bundler/dry-validation-1.4.1
```

**Comment by mislav** [comment]
@elashpear If you find the time, please try this to see if it's fixed for you too!

@saiqulhaq Thank you for the update! 🙇

**Comment by OliverJAsh** [comment]
I'm also running into this problem. I wanted to try the new version, but I get this:

```sh-session
$ brew upgrade gh
Warning: github/gh/gh 9.9.10 already installed
```

Any ideas @mislav?

**Comment by mislav** [comment]
@OliverJAsh Sorry about that, I think that was a release snafu on our end.

Please do `brew update && brew reinstall gh`
